[package]
name = "funny_string"
version = "0.1.0"
authors = ["Wouter Pennings"]
edition = "2018"
license = "MIT"
repository = "https://github.com/WouterPennings/string_helper.git"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
